# Generated by Django 5.0.6 on 2024-05-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vid',
            name='cap_fil',
            field=models.FileField(null=True, upload_to='subtitles/'),
        ),
        migrations.AlterField(
            model_name='vid',
            name='url',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
