# Generated by Django 5.0.6 on 2024-05-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgen', '0002_vid_cap_fil_alter_vid_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='vid',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='vid',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
