# Generated by Django 5.0.6 on 2024-05-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgen', '0003_vid_image_vid_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vid',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
