# Generated by Django 5.0.6 on 2024-05-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgen', '0004_vid_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vid',
            name='urll',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='vid',
            name='url',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
